import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    // jsdom because a few units under test read from the DOM (computeColor
    // resolves CSS custom properties via getComputedStyle).
    environment: 'jsdom',
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      // Generated by ts-interface-builder, not hand-written code.
      exclude: ['src/types-config-ti.ts'],
    },
  },
});
